attendant:
  basic_reward_functions:
  - name: reward_reach_object_hof
  basic_reward_weights:
  - 1
  model_source: gpt
  query_source: openai
  skills:
  - move_right_1_steps
  - forward
  - move_right_4_steps
  - right
  - move_right_3_steps
  - move_right_5_steps
  - move_right_2_steps
env_specs:
  principal_level: EMPTY
  seed: 1
  task: GOTO
principal:
  basic_reward_functions:
  - name: reward_reach_object_hof
  basic_reward_weights:
  - 1
  query_source: openai
  skills:
  - ''
