task: PICKUP
roles: 
  executor: human
  observer: ai
  solver: ai
human:
  model_source: gpt
  query_source: openai
  preference:
    - reward_carry_object_hof: 1
  skillset:
    - left
    - right
    - forward
    - pickup
    - drop
    - toggle
    - done
  world_model:
    task: PICKUP
    layout: ROOM_DOOR_KEY
    edits: [FLIP_VERTICAL, DOUBLE_GRID_SIZE, CHANGE_TARGET_COLOR, HIDE_TARGETS_IN_BOXES, CHANGE_AGENT_VIEW_SIZE, PUT_AGENT_IN_ROOM, ADD_OPENING_TO_WALL, ADD_DOOR, TOGGLE_DOORS, BLOCK_DOORS]
    seed: 1
    allowed_object_colors: ["green", "blue"]
ai:
  model_source: gpt
  query_source: openai
  preference:
    - reward_carry_object_hof: 1
  skillset:
    - left
    - right
    - forward
    - pickup
    - drop
    - toggle
    - done
  world_model:
    task: PICKUP
    layout: TREASURE_ISLAND
    edits: [FLIP_VERTICAL, DOUBLE_GRID_SIZE, CHANGE_TARGET_COLOR, HIDE_TARGETS_IN_BOXES, CHANGE_AGENT_VIEW_SIZE, PUT_AGENT_ON_ISLAND, ADD_BRIDGE, MAKE_LAVA_SAFE, ADD_FIREPROOF_SHOES, BLOCK_BRIDGES]
    seed: 23
    allowed_object_colors: ["green", "blue"]
