principal:
  reward_functions:
    - has_reached_box
  reward_weights:
    - 1
  skills:
    - go_forward
    - go_left
    - go_right
    - go_behind
    - go_to_ball
    - go_to_box
    - go_to_goal
    - go_to_key
    - go_to_wall
    - go_to_lava
    - go_to_door
    - pick_up_ball
    - pick_up_box
    - pick_up_key
    - put_down_ball
    - put_down_box
    - put_down_key
    - open_door
    - open_box
    - unlock_door
    - close_door

attendant:
  reward_functions:
    - has_reached_box
  reward_weights:
    - 1
  skills:
    - go_to_ball
    - go_to_box
    - go_to_door
    - go_to_key
    - unlock_door
    - pick_up_key
    - pick_up_box

env_specs:
  task: GOTO
  principal_level: EMPTY
  attendant_level: UNLOCK_DOOR
  seed: 3